with-expecter: true
resolve-type-alias: false
issue-845-fix: true
packages:
  github.com/benbjohnson/clock:
    config:
      dir: "internal/pkg/mock"
      outpkg: "mock"
      filename: "{{.InterfaceName | snakecase}}.go"
    interfaces:
      Clock:
  github.com/xabsvoid/tracker/internal/app/geo/repository:
    config:
      dir: "internal/pkg/mock"
      outpkg: "mock"
      filename: "{{.InterfaceName | snakecase}}.go"
    interfaces:
      Location:
